name: Deploy Java JAR to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build JAR file
        run: |
          cd server 
          mvn clean package -DskipTests

      - name: Transfer JAR to EC2
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "server/target/society_management-0.0.1-SNAPSHOT.jar"
          target: "/home/ubuntu/"

      - name: Deploy and Restart Application
        run: |
          chmod 400 server/key.pem
          scp -i server/key.pem society_management-0.0.1-SNAPSHOT.jar ubuntu@${{ secrets.EC2_HOST }}:/home/ubuntu/
          ssh -i server/key.pem ubuntu@${{ secrets.EC2_HOST }} << EOF
            pkill -f 'java -jar society_management-0.0.1-SNAPSHOT.jar' || true
            nohup java -jar /home/ubuntu/society_management-0.0.1-SNAPSHOT.jar > /home/ubuntu/output.log 2>&1 &
          EOF
